### ISSUE TITLE
It Stops with a # at line head in python

### ISSUE THREAD

**Issue by AlynxZhou** [zk-phi/indent-guide#45]
With a # in the head,it stops show below the # line.

Also when going down it's slow,only when you stop going down it shows again.However,going up doesn't,if you press C-p a long time,the indent guide will refresh every line your cursor get,while it only display when you stop going down,not each line,sometimes it causes emacs stuck.

**Comment by zk-phi** [comment]
> With a # in the head,it stops show below the # line.

Since indent-guide just recognizes the indentation (number of spaces), but not the language's syntax, `#` at the leftmost column is considered as a block-end by indent-guide.

```
Also when going down it's slow,only when you stop going down it shows again.
```

indent-guide does not change the behavior either you are going down or not, so I'm not sure why it occurs. (A possible work-around may be setting indent-guide-delay to enable lazy highlight)

**Comment by zk-phi** [comment]
Closing.
